# TODO: Bump Ruby to 2.5.0
# ref. https://github.com/rails/spring/issues/550
FROM ruby:2.4.3-alpine
LABEL maintainer "cheezenaan <cheezenaan@gmail.com>"

ENV LANG C.UTF-8

# Install dependencies
RUN set -x && \
  apk update && apk upgrade && \
  apk add --no-cache openssl wget build-base libxml2-dev libxslt-dev mysql-dev mysql-client nodejs tzdata chromium

# Install Entrykit
ENV ENTRYKIT_VERSION 0.4.0
RUN wget https://github.com/progrium/entrykit/releases/download/v${ENTRYKIT_VERSION}/entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && tar -xvzf entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && rm entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && mv entrykit /bin/entrykit \
  && chmod +x /bin/entrykit \
  && entrykit --symlink

ENV APP_ROOT /app
WORKDIR $APP_ROOT

RUN bundle config build.nokogiri --use-system-libraries

ENTRYPOINT [ \
  "prehook", "ruby -v", "--", \
  "prehook", "bundle install -j4 --quiet --path vendor/bundle", "--" \
]
