# TODO: Bump Ruby to 2.5.0
# ref. https://github.com/rails/spring/issues/550
FROM ruby:2.4.3-alpine3.7
LABEL maintainer "cheezenaan <cheezenaan@gmail.com>"

ENV \
  APP_ROOT="/app" \
  DEV_PACKAGES="build-base libxml2-dev libxslt-dev tzdata" \
  DOCKERIZE_VERSION="v0.3.0" \
  ENTRYKIT_VERSION="0.4.0" \
  LANG="C.UTF-8" \
  RAILS_PACKAGES="mysql-dev imagemagick"

WORKDIR $APP_ROOT

COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock

# Install dependencies
RUN \
  set -x && \
  apk update && apk upgrade && apk add --no-cache $DEV_PACKAGES $RAILS_PACKAGES && \
  #
  # Set timezone
  cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
  #
  # Install Entrykit & Dockerize
  wget https://github.com/progrium/entrykit/releases/download/v${ENTRYKIT_VERSION}/entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz && \
  tar -xvzf entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz && \
  rm entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz && \
  mv entrykit /bin/entrykit && \
  chmod +x /bin/entrykit && \
  entrykit --symlink && \
  wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
  tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
  rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
  #
  # Install gems
  bundle config build.nokogiri --use-system-libraries && \
  bundle install -j4 --quiet --path vendor/bundle

COPY . $APP_ROOT

ENTRYPOINT [ \
  "prehook", "ruby -v", "--", \
  "prehook", "dockerize -timeout 60s -wait tcp://${DATABASE_HOST}:3306", "--" \
  ]
