FROM node:9.11.2-alpine
LABEL maintainer "cheezenaan <cheezenaan@gmail.com>"

ENV \
  APP_ROOT="/app"

WORKDIR ${APP_ROOT}/frontend

# TODO: Divide Dockerfile into development and test(prod) environments
